# Generated by Django 4.0.5 on 2022-06-18 07:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Не более 200 символов', max_length=200, verbose_name='Наименование')),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Не более 5000 символов', max_length=5000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('likes_post', models.ManyToManyField(blank=True, related_name='like_post', to=settings.AUTH_USER_MODEL, verbose_name='Лайкнутые посты')),
                ('saved_post', models.ManyToManyField(blank=True, related_name='saved_post', to=settings.AUTH_USER_MODEL, verbose_name='Сохраненные посты')),
            ],
            options={
                'verbose_name': 'Создать пост',
                'verbose_name_plural': 'Создать посты',
            },
        ),
    ]
